	nios_core u0 (
		.audio_xck                                  (<connected-to-audio_xck>),                                  //            audio.xck
		.audio_daclrc                               (<connected-to-audio_daclrc>),                               //                 .daclrc
		.audio_dacdat                               (<connected-to-audio_dacdat>),                               //                 .dacdat
		.audio_bclk                                 (<connected-to-audio_bclk>),                                 //                 .bclk
		.audio_adclrc                               (<connected-to-audio_adclrc>),                               //                 .adclrc
		.audio_adcdat                               (<connected-to-audio_adcdat>),                               //                 .adcdat
		.clk_clk                                    (<connected-to-clk_clk>),                                    //              clk.clk
		.ddr3_pll_ref_clk_clk                       (<connected-to-ddr3_pll_ref_clk_clk>),                       // ddr3_pll_ref_clk.clk
		.ddr3_pll_sharing_pll_mem_clk               (<connected-to-ddr3_pll_sharing_pll_mem_clk>),               // ddr3_pll_sharing.pll_mem_clk
		.ddr3_pll_sharing_pll_write_clk             (<connected-to-ddr3_pll_sharing_pll_write_clk>),             //                 .pll_write_clk
		.ddr3_pll_sharing_pll_locked                (<connected-to-ddr3_pll_sharing_pll_locked>),                //                 .pll_locked
		.ddr3_pll_sharing_pll_write_clk_pre_phy_clk (<connected-to-ddr3_pll_sharing_pll_write_clk_pre_phy_clk>), //                 .pll_write_clk_pre_phy_clk
		.ddr3_pll_sharing_pll_addr_cmd_clk          (<connected-to-ddr3_pll_sharing_pll_addr_cmd_clk>),          //                 .pll_addr_cmd_clk
		.ddr3_pll_sharing_pll_avl_clk               (<connected-to-ddr3_pll_sharing_pll_avl_clk>),               //                 .pll_avl_clk
		.ddr3_pll_sharing_pll_config_clk            (<connected-to-ddr3_pll_sharing_pll_config_clk>),            //                 .pll_config_clk
		.ddr3_pll_sharing_pll_mem_phy_clk           (<connected-to-ddr3_pll_sharing_pll_mem_phy_clk>),           //                 .pll_mem_phy_clk
		.ddr3_pll_sharing_afi_phy_clk               (<connected-to-ddr3_pll_sharing_afi_phy_clk>),               //                 .afi_phy_clk
		.ddr3_pll_sharing_pll_avl_phy_clk           (<connected-to-ddr3_pll_sharing_pll_avl_phy_clk>),           //                 .pll_avl_phy_clk
		.ddr3_status_local_init_done                (<connected-to-ddr3_status_local_init_done>),                //      ddr3_status.local_init_done
		.ddr3_status_local_cal_success              (<connected-to-ddr3_status_local_cal_success>),              //                 .local_cal_success
		.ddr3_status_local_cal_fail                 (<connected-to-ddr3_status_local_cal_fail>),                 //                 .local_cal_fail
		.i2c_scl_export                             (<connected-to-i2c_scl_export>),                             //          i2c_scl.export
		.i2c_sda_export                             (<connected-to-i2c_sda_export>),                             //          i2c_sda.export
		.memory_mem_a                               (<connected-to-memory_mem_a>),                               //           memory.mem_a
		.memory_mem_ba                              (<connected-to-memory_mem_ba>),                              //                 .mem_ba
		.memory_mem_ck                              (<connected-to-memory_mem_ck>),                              //                 .mem_ck
		.memory_mem_ck_n                            (<connected-to-memory_mem_ck_n>),                            //                 .mem_ck_n
		.memory_mem_cke                             (<connected-to-memory_mem_cke>),                             //                 .mem_cke
		.memory_mem_cs_n                            (<connected-to-memory_mem_cs_n>),                            //                 .mem_cs_n
		.memory_mem_dm                              (<connected-to-memory_mem_dm>),                              //                 .mem_dm
		.memory_mem_ras_n                           (<connected-to-memory_mem_ras_n>),                           //                 .mem_ras_n
		.memory_mem_cas_n                           (<connected-to-memory_mem_cas_n>),                           //                 .mem_cas_n
		.memory_mem_we_n                            (<connected-to-memory_mem_we_n>),                            //                 .mem_we_n
		.memory_mem_reset_n                         (<connected-to-memory_mem_reset_n>),                         //                 .mem_reset_n
		.memory_mem_dq                              (<connected-to-memory_mem_dq>),                              //                 .mem_dq
		.memory_mem_dqs                             (<connected-to-memory_mem_dqs>),                             //                 .mem_dqs
		.memory_mem_dqs_n                           (<connected-to-memory_mem_dqs_n>),                           //                 .mem_dqs_n
		.memory_mem_odt                             (<connected-to-memory_mem_odt>),                             //                 .mem_odt
		.oct_rzqin                                  (<connected-to-oct_rzqin>),                                  //              oct.rzqin
		.pio_key_export                             (<connected-to-pio_key_export>),                             //          pio_key.export
		.pio_led_export                             (<connected-to-pio_led_export>),                             //          pio_led.export
		.pio_sw_export                              (<connected-to-pio_sw_export>),                              //           pio_sw.export
		.reset_reset_n                              (<connected-to-reset_reset_n>),                              //            reset.reset_n
		.vga_vga_clk                                (<connected-to-vga_vga_clk>),                                //              vga.vga_clk
		.vga_vga_hs                                 (<connected-to-vga_vga_hs>),                                 //                 .vga_hs
		.vga_vga_vs                                 (<connected-to-vga_vga_vs>),                                 //                 .vga_vs
		.vga_vga_de                                 (<connected-to-vga_vga_de>),                                 //                 .vga_de
		.vga_vga_r                                  (<connected-to-vga_vga_r>),                                  //                 .vga_r
		.vga_vga_g                                  (<connected-to-vga_vga_g>),                                  //                 .vga_g
		.vga_vga_b                                  (<connected-to-vga_vga_b>),                                  //                 .vga_b
		.vga_clk_clk                                (<connected-to-vga_clk_clk>)                                 //          vga_clk.clk
	);

